---
product: "1.0.0"
info:
  name: "appproyecto"
  title: "APP_Proyecto"
  version: "1.0.0"
visibility:
  view:
    enabled: true
    type: "public"
    tags: []
    orgs: []
  subscribe:
    enabled: true
    type: "authenticated"
    tags: []
    orgs: []
apis:
  consultarcliente:
    $ref: "consultar-Reclamo-Cliente_1.0.0.yaml"
plans:
  default:
    title: "Default Plan"
    description: "Default Plan"
    approval: false
    rate-limit:
      hard-limit: true
      value: "12000/12hour"
